if(NOT DEFINED WORKFLOW)
    message(FATAL_ERROR "WORKFLOW variable is required")
endif()

if(NOT EXISTS "${WORKFLOW}")
    message(FATAL_ERROR "workflow file not found: ${WORKFLOW}")
endif()

file(READ "${WORKFLOW}" workflow_text)

if(NOT workflow_text MATCHES "name:[ \t]*LFortran API Compatibility \\(WITH_LIRIC\\)")
    message(FATAL_ERROR "missing workflow name in ${WORKFLOW}")
endif()
if(NOT workflow_text MATCHES "Run LFortran full suites with WITH_LIRIC")
    message(FATAL_ERROR "workflow missing WITH_LIRIC full-suite step")
endif()
if(NOT workflow_text MATCHES "\\./tools/lfortran_mass/lfortran_api_compat\\.sh")
    message(FATAL_ERROR "workflow must execute tools/lfortran_mass/lfortran_api_compat.sh")
endif()
if(NOT workflow_text MATCHES "--fresh-workspace")
    message(FATAL_ERROR "workflow must enforce clean-clone runs via --fresh-workspace")
endif()
if(NOT workflow_text MATCHES "--run-ref-tests[ \t]+yes")
    message(FATAL_ERROR "workflow must run reference suite in WITH_LIRIC lane")
endif()
if(NOT workflow_text MATCHES "--run-itests[ \t]+yes")
    message(FATAL_ERROR "workflow must run integration suite in WITH_LIRIC lane")
endif()
