if(NOT DEFINED WORKFLOW)
    message(FATAL_ERROR "WORKFLOW variable is required")
endif()

if(NOT EXISTS "${WORKFLOW}")
    message(FATAL_ERROR "workflow file not found: ${WORKFLOW}")
endif()

file(READ "${WORKFLOW}" workflow_text)

if(NOT workflow_text MATCHES "name:[ \t]*LFortran API Compatibility \\(WITH_LIRIC\\)")
    message(FATAL_ERROR "missing workflow name in ${WORKFLOW}")
endif()
if(NOT workflow_text MATCHES "Run LFortran full suites with WITH_LIRIC")
    message(FATAL_ERROR "workflow missing WITH_LIRIC full-suite step")
endif()
if(NOT workflow_text MATCHES "Configure liric \\+ LFortran dependency roots")
    message(FATAL_ERROR "workflow must configure liric with CMake-managed LFortran dependency roots")
endif()
if(NOT workflow_text MATCHES "LIRIC_LFORTRAN_REPO")
    message(FATAL_ERROR "workflow must set LIRIC_LFORTRAN_REPO for dependency resolution")
endif()
if(NOT workflow_text MATCHES "LIRIC_LFORTRAN_REF")
    message(FATAL_ERROR "workflow must set LIRIC_LFORTRAN_REF for dependency resolution")
endif()
if(NOT workflow_text MATCHES "--target[ \t]+lfortran_api_compat")
    message(FATAL_ERROR "workflow must execute CMake lfortran_api_compat target")
endif()
