if(NOT DEFINED WORKFLOW)
    message(FATAL_ERROR "WORKFLOW variable is required")
endif()

if(NOT EXISTS "${WORKFLOW}")
    message(FATAL_ERROR "workflow file not found: ${WORKFLOW}")
endif()

file(READ "${WORKFLOW}" workflow_text)

if(NOT workflow_text MATCHES "name:[ \t]*LLVM Backend Compat")
    message(FATAL_ERROR "missing workflow name in ${WORKFLOW}")
endif()
if(NOT workflow_text MATCHES "llvm-version:[ \t]*\\[\"7\"")
    message(FATAL_ERROR "workflow matrix must include LLVM major 7")
endif()
if(NOT workflow_text MATCHES "\"21\"\\]")
    message(FATAL_ERROR "workflow matrix must include LLVM major 21")
endif()
if(NOT workflow_text MATCHES "with_compat=OFF")
    message(FATAL_ERROR "workflow must default compat OFF")
endif()
if(NOT workflow_text MATCHES "\\[\\[ \"\\$\\{\\{ matrix\\.llvm-version \\}\\}\" -ge 11 \\]\\]")
    message(FATAL_ERROR "workflow must gate compat enablement on LLVM >= 11")
endif()
if(NOT workflow_text MATCHES "with_compat=ON")
    message(FATAL_ERROR "workflow must enable compat for supported LLVM majors")
endif()
if(NOT workflow_text MATCHES "-DWITH_REAL_LLVM_BACKEND=ON")
    message(FATAL_ERROR "workflow must build with real LLVM backend enabled")
endif()
if(NOT workflow_text MATCHES "-DWITH_LLVM_COMPAT=\"\\$\\{with_compat\\}\"")
    message(FATAL_ERROR "workflow must pass computed compat policy to CMake")
endif()
