if(NOT DEFINED WORKFLOW)
    message(FATAL_ERROR "WORKFLOW variable is required")
endif()

if(NOT EXISTS "${WORKFLOW}")
    message(FATAL_ERROR "workflow file not found: ${WORKFLOW}")
endif()

file(READ "${WORKFLOW}" workflow_text)

if(NOT workflow_text MATCHES "name:[ \t]*Nightly Mass Campaign")
    message(FATAL_ERROR "missing workflow name in ${WORKFLOW}")
endif()
if(NOT workflow_text MATCHES "schedule:")
    message(FATAL_ERROR "missing schedule trigger in ${WORKFLOW}")
endif()
if(NOT workflow_text MATCHES "workflow_dispatch:")
    message(FATAL_ERROR "missing workflow_dispatch trigger in ${WORKFLOW}")
endif()
if(NOT workflow_text MATCHES "os:[ \t]*\\[ubuntu-latest,[ \t]*macos-14\\]")
    message(FATAL_ERROR "workflow matrix must include ubuntu-latest and macos-14")
endif()
if(NOT workflow_text MATCHES "\\./tools/lfortran_mass/nightly_mass\\.sh")
    message(FATAL_ERROR "workflow must execute tools/lfortran_mass/nightly_mass.sh")
endif()
if(NOT workflow_text MATCHES "\\./tools/bench_api_clean_gate\\.sh")
    message(FATAL_ERROR "workflow must execute tools/bench_api_clean_gate.sh")
endif()
if(NOT workflow_text MATCHES "\\./tools/bench_readme_perf_gate\\.sh")
    message(FATAL_ERROR "workflow must execute tools/bench_readme_perf_gate.sh")
endif()
if(workflow_text MATCHES "python3 -m tools\\.lfortran_mass\\.run_mass")
    message(FATAL_ERROR "workflow must not depend on python mass runner")
endif()
if(NOT workflow_text MATCHES "Build lfortran WITH_LIRIC")
    message(FATAL_ERROR "workflow must build lfortran WITH_LIRIC for API clean-pass gate")
endif()
if(NOT workflow_text MATCHES "WITH_LIRIC")
    message(FATAL_ERROR "workflow missing WITH_LIRIC configuration")
endif()
if(NOT workflow_text MATCHES "Run API clean-pass gate")
    message(FATAL_ERROR "workflow missing API clean-pass gate step")
endif()
if(NOT workflow_text MATCHES "README benchmark snapshot contract")
    message(FATAL_ERROR "workflow missing README benchmark snapshot validation step")
endif()
if(NOT workflow_text MATCHES "gate")
    message(FATAL_ERROR "workflow should include explicit regression-gate step wording")
endif()
if(NOT workflow_text MATCHES "manifest_tests_toml\\.jsonl")
    message(FATAL_ERROR "manifest artifact path missing")
endif()
if(NOT workflow_text MATCHES "results\\.jsonl")
    message(FATAL_ERROR "results artifact path missing")
endif()
if(NOT workflow_text MATCHES "summary\\.json")
    message(FATAL_ERROR "summary artifact path missing")
endif()
if(NOT workflow_text MATCHES "runnable_selected_executable")
    message(FATAL_ERROR "workflow trend summary must report runnable_selected_executable")
endif()
if(NOT workflow_text MATCHES "differential_attempted_executable")
    message(FATAL_ERROR "workflow trend summary must report differential_attempted_executable")
endif()
if(NOT workflow_text MATCHES "differential_missing_attempts")
    message(FATAL_ERROR "workflow trend summary must report differential_missing_attempts")
endif()
if(NOT workflow_text MATCHES "failures\\.csv")
    message(FATAL_ERROR "failures artifact path missing")
endif()
if(NOT workflow_text MATCHES "bench_api_clean_gate/bench_api_summary\\.json")
    message(FATAL_ERROR "bench_api clean-gate summary artifact path missing")
endif()
if(NOT workflow_text MATCHES "actions/cache/restore@v4")
    message(FATAL_ERROR "baseline cache restore step missing")
endif()
if(NOT workflow_text MATCHES "actions/cache/save@v4")
    message(FATAL_ERROR "baseline cache save step missing")
endif()
