if(NOT DEFINED WORKFLOW)
    message(FATAL_ERROR "WORKFLOW variable is required")
endif()

if(NOT EXISTS "${WORKFLOW}")
    message(FATAL_ERROR "workflow file not found: ${WORKFLOW}")
endif()

file(READ "${WORKFLOW}" workflow_text)

if(NOT workflow_text MATCHES "name:[ \t]*LLVM Backend Compat")
    message(FATAL_ERROR "missing workflow name in ${WORKFLOW}")
endif()
if(NOT workflow_text MATCHES "discover-llvmdev")
    message(FATAL_ERROR "workflow must include llvmdev discovery job")
endif()
if(NOT workflow_text MATCHES "micromamba search -c conda-forge llvmdev --json")
    message(FATAL_ERROR "workflow must discover llvmdev versions from conda-forge")
endif()
if(NOT workflow_text MATCHES "\\$1 >= 3 && \\$1 <= 22")
    message(FATAL_ERROR "workflow discovery must bound majors to 3..22")
endif()
if(NOT workflow_text MATCHES "fromJSON\\(needs\\.discover-llvmdev\\.outputs\\.versions\\)")
    message(FATAL_ERROR "workflow matrix must use discovered version JSON")
endif()
if(NOT workflow_text MATCHES "with_compat=OFF")
    message(FATAL_ERROR "workflow must default compat OFF")
endif()
if(NOT workflow_text MATCHES "\\[\\[ \"\\$\\{\\{ matrix\\.llvm-version \\}\\}\" -ge 11 \\]\\]")
    message(FATAL_ERROR "workflow must gate compat enablement on LLVM >= 11")
endif()
if(NOT workflow_text MATCHES "with_compat=ON")
    message(FATAL_ERROR "workflow must enable compat for supported LLVM majors")
endif()
if(NOT workflow_text MATCHES "-DWITH_REAL_LLVM_BACKEND=ON")
    message(FATAL_ERROR "workflow must build with real LLVM backend enabled")
endif()
if(NOT workflow_text MATCHES "-DWITH_LLVM_COMPAT=\"\\$\\{with_compat\\}\"")
    message(FATAL_ERROR "workflow must pass computed compat policy to CMake")
endif()
